Feat/8 - vrátit naskenovaná data
madebyqwerty/ocr-service pull request #14
Opened 2023-05-26 17:46 UTC by Venca321

2023-05-26 18:21 UTC, tomaskebrle requested changes

2023-05-26 18:21 UTC, tomaskebrle commented on main.py
> +            description: Bad or missing image
Možná bych dal rozdíl mezi missing image což bude pravděpodobně chyba naše že jsme to poslali blbě, a mezi špatným obrázkem což je chyba uživatele, a tu chybu bych mu potom vrátil

2023-05-26 18:21 UTC, tomaskebrle commented on main.py
> +            description: Bad or missing image
Ale tohle bychh už udělal v dalším PR

2023-05-26 18:21 UTC, tomaskebrle commented on ocr.py
> +        url = "http://192.168.0.10:3002/api/users"
Na localhostu to nefunguje? protože tohle je pokud se nepletu lokální adresa která myslím bude pro každého jiná

2023-05-26 18:23 UTC, Venca321 commented on ocr.py
> +        url = "http://192.168.0.10:3002/api/users"
Mělo by fungovat i na localhostu, tohle jsem testoval a zapomněl to přepsat xD

2023-05-27 20:27 UTC, tomaskebrle approved these changes

2023-05-27 20:27 UTC, tomaskebrle commented on main.py
> +        if file and file.filename.endswith(allowed):
nejde nějak získat file koncovku a pak udělat něco jako v JS `.includes`?

2023-05-28 07:26 UTC, merged