Feat/5 - Qrcody a otočení papíru
madebyqwerty/ocr-service pull request #7
Opened 2023-05-01 14:42 UTC by Venca321

2023-05-01 18:19 UTC, tomaskebrle requested changes

2023-05-01 18:19 UTC, tomaskebrle commented on main.py
> +        filtered_img = cv2.medianBlur(thresh_img, 81) #Filter showing approximate shape of the paper
Ta 81 je nějaká random hodnota nebo kde se vzala?

2023-05-01 18:19 UTC, tomaskebrle commented on main.py
> +        raise NotImplementedError #No readable qrcode on img
Jsem trochu zmatený, NotImplementedError je že jsi něco neimplementoval? Tohle by mělo být spíš nějaký CouldNotFindQrCodeError, nebo něco podobného?

2023-05-02 05:46 UTC, Venca321 commented on main.py
> +        filtered_img = cv2.medianBlur(thresh_img, 81) #Filter showing approximate shape of the paper
To je velikost mediánového filtru, kterou jsem našel tím, že jsem zkoušel, kdy jsou hrany papíru nejlépe vidět.

2023-05-02 05:49 UTC, Venca321 commented on main.py
> +        raise NotImplementedError #No readable qrcode on img
Jo, já jsem tam dal NotImplementedError, abych tam něco měl, asi ho tam nechám než budu vědět, jak bude vypadat výstup a podle toho to upravím. (Možná bude nějaký lepší způsob, než dávat error)

2023-05-02 15:51 UTC, tomaskebrle commented on main.py
> +        filtered_img = cv2.medianBlur(thresh_img, 81) #Filter showing approximate shape of the paper
No možná bych to dal do vlastní variably, ale stejnak na tom budeš dělat jenom ty

2023-05-02 15:53 UTC, tomaskebrle commented on main.py
> +        raise NotImplementedError #No readable qrcode on img
Nejsem si jistý k čemu potřebuješ vědet jak vypadá výstup, nevím jak fungujou error v Pythonu ale v JS bych udělal asi něco takovýho
```js
throw new Error("qrcode/not-readeable")
// Nebo
throw new Error("QRCode is not readable")
```

2023-05-02 16:03 UTC, Venca321 commented on main.py
> +        filtered_img = cv2.medianBlur(thresh_img, 81) #Filter showing approximate shape of the paper
Mě to přijde trochu zbytečný, ale pokud to chceš, tak to můžu udělat

2023-05-02 16:04 UTC, Venca321 commented on main.py
> +        raise NotImplementedError #No readable qrcode on img
Opraveno

2023-05-03 06:07 UTC, tomaskebrle approved these changes

2023-05-03 06:08 UTC, merged